version: '3.8'
services:
  web:
    image: nginx
    ports:
    - "8080:80"
    volumes:
      - ./app:/var/www/path
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: path
      MYSQL_USER: path
      MYSQL_PASSWORD: path
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - '3306:3306'
  php:
    container_name: php
    build:
      context: ./php
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/path
    depends_on:
      - db
